#!/bin/bash
#users=$(awk -F: '{print "User name: " $1 "		User ID: " $3"	 Group ID: " $4}' /etc/passwd)

#whiptail --scrolltext --msgbox "$users" 20 70 --title "List of Users"


# Use awk to format the output with the desired format
Users=$(awk -F: 'BEGIN{printf "%-20s %-10s %-10s\n", "User Name", "User ID", "Group ID"} {printf "%-20s %-10s %-10s\n", $1, $3, $4}' /etc/passwd )

# Use whiptail to display the list of users
whiptail --msgbox --scrolltext "$Users" 30 70 --title "List of Users"
