#!/bin/bash
#awk used to format the output
#Groups=$(awk -F: '{print "Group name: " $1 "\t Group ID: " $3}' /etc/group)
#Groups=$(awk -F: '{printf("Group name: %s\tGroup ID: %s\n", $1, $3)}' /etc/group)
#use whiptail to display the list of users 
#whiptail  --msgbox --scrolltext "$Groups" 20 70 --title "List of groups"
##!/bin/bash

# Use awk to format the output
Groups=$(awk -F: '{printf("Group name = %s:GID = %s\n", $1, $3)}' /etc/group)

# Use column to format the output into three columns
Groups_formatted=$(echo "$Groups" | column -t -s: -c2)

# Use whiptail to display the list of groups
whiptail --msgbox --scrolltext "$Groups_formatted" 20 70 --title "List of groups"

